# Generated by Django 3.0.5 on 2020-06-29 12:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20200629_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 15, 47, 34, 949755)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='bloglikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
