# Generated by Django 3.0.6 on 2021-02-11 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210203_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 11, 14, 27, 0, 888472)),
        ),
    ]
