# Generated by Django 3.0.5 on 2020-05-07 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 7, 14, 10, 8, 547088))),
                ('url', models.URLField(blank=None)),
                ('img', models.ImageField(upload_to='media/picturesIT')),
                ('description', models.TextField()),
            ],
        ),
    ]
