# Generated by Django 3.0.5 on 2020-06-29 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginait', '0003_auto_20200629_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursit',
            name='isliked',
            field=models.ManyToManyField(blank=True, default=None, related_name='itlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cursit',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 15, 47, 34, 949755)),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itpost', to='paginait.Cursit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ituser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
