# Generated by Django 3.0.5 on 2020-06-29 12:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginait', '0004_auto_20200629_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Liked',
        ),
        migrations.AlterField(
            model_name='cursit',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 15, 55, 36, 145989)),
        ),
    ]
