# Generated by Django 3.0.6 on 2021-02-03 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginait', '0005_auto_20200629_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursit',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 3, 13, 42, 53, 511717)),
        ),
    ]
